---
dist: Focal

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - git
      - python-pip

install:
  - pip install -r tests/requirements.txt
  - pip install ansible-lint==4.2.0
script:
  - |
    if [[ -n $(grep --exclude-dir=.git -P "\xa0" -r .) ]]; then
      echo 'NBSP characters found'
      exit 1
    fi

  - |
    for i in $(ls -1 roles/); do
      ANSIBLE_LOG_PATH=/dev/null
      ansible-lint -x 701,702,703,704 \
        --exclude=roles/git_sparse_checkout \
        --exclude=roles/pre_roles/common/meta \
        --exclude=roles/post_roles/common/meta \
        --exclude=roles/${i}/meta \
        -v roles/${i}
      if [ $? -ne 0 ]; then
        exit 1
      fi
    done

  - |
    ansible-playbook -e project=test -e author=test --check -v site.yml
    if [ $? -ne 0 ]; then
        exit 1
    fi
