---
- name: "<r_common_t_add_gitignore> copy dot_gitignore to {{ project_path }}/.gitignore"
  copy:
    # if path ends with "/", only inside contents of that
    # directory are copied to destination.
    # if it does not end with "/", the directory itself
    # with all contents is copied.
    src: dot_gitignore
    dest: "{{ project_path }}/.gitignore"
    #owner:
    #group:
    #mode:
    #backup: yes
    # The validation command to run before copying into place.
    # E.g. `validate: /usr/sbin/visudo -csf %s`
    #validate:
